services:
  proxy:
    container_name: jstream-proxy
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
  app:
    container_name: jstream-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html
  db:
    container_name: jstream-db
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - jstream-db-volume:/var/lib/mysql
    environment:
       MYSQL_DATABASE: laravel_db
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: user 
       MYSQL_PASSWORD: password
  phpmyadmin:
    container_name: jstream-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=root
volumes:
  jstream-db-volume: